# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gardaltetmo/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/es305_fw.bin:system/vendor/firmware/es305_fw.bin \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/srp_cga.bin:system/vendor/firmware/srp_cga.bin \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/srp_data.bin:system/vendor/firmware/srp_data.bin \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/srp_vliw.bin:system/vendor/firmware/srp_vliw.bin \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/bcm4334.hcd:system/vendor/firmware/bcm4334.hcd \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/BT_FW_VER_BCM4334B0_002.001.013.1810.2178_Garda_ORC.hcd:system/vendor/firmware/BT_FW_VER_BCM4334B0_002.001.013.1810.2178_Garda_ORC.hcd \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/es305_fw_bypass.bin:system/vendor/firmware/es305_fw_bypass.bin \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/fimc_is_fw2.bin:system/vendor/firmware/fimc_is_fw2.bin \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/libpn547_fw_pku.so:system/vendor/firmware/libpn547_fw_pku.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/libpn547_fw_platform.so:system/vendor/firmware/libpn547_fw_platform.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/setfile_4h5.bin:system/vendor/firmware/setfile_4h5.bin \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/setfile_6a3.bin:system/vendor/firmware/setfile_6a3.bin \
    vendor/samsung/gardaltetmo/proprietary/vendor/firmware/setfile_6b2.bin:system/vendor/firmware/setfile_6b2.bin \
    vendor/samsung/gardaltetmo/proprietary/lib/hw/audio.primary.universal3470.so:system/lib/hw/audio.primary.universal3470.so \
    vendor/samsung/gardaltetmo/proprietary/lib/hw/audio_policy.universal3470.so:system/lib/hw/audio_policy.universal3470.so \
    vendor/samsung/gardaltetmo/proprietary/lib/hw/gralloc.exynos3.so:system/lib/hw/gralloc.exynos3.so \
    vendor/samsung/gardaltetmo/proprietary/lib/hw/nfc.universal3470.so:system/lib/hw/nfc.universal3470.so \
    vendor/samsung/gardaltetmo/proprietary/lib/hw/sensors.universal3470.so:system/lib/hw/sensors.universal3470.so \
    vendor/samsung/gardaltetmo/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libakm.so:system/lib/libakm.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libExynosHWCService.so:system/lib/libExynosHWCService.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libExynosOMX263d.so:system/lib/libExynosOMX263d.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libExynosOMX264d.so:system/lib/libExynosOMX264d.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libExynosOMXCmn.so:system/lib/libExynosOMXCmn.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libExynosOMXCore.so:system/lib/libExynosOMXCore.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libExynosOMXMp4vd.so:system/lib/libExynosOMXMp4vd.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/gardaltetmo/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/gardaltetmo/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/gardaltetmo/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/gardaltetmo/proprietary/lib/omx/libOMX.Exynos.MP3.Decoder.so:system/lib/omx/libOMX.Exynos.MP3.Decoder.so \
    vendor/samsung/gardaltetmo/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/gardaltetmo/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/gardaltetmo/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/gardaltetmo/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/gardaltetmo/proprietary/lib/egl/libGLESv2_mali.so:system/vendor/lib/egl/libGLESv2_mali.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/liblvverx.so:system/vendor/lib/liblvverx.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/liblvverx_3.21.15.so:system/vendor/lib/liblvverx_3.21.15.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/liblvvetx.so:system/vendor/lib/liblvvetx.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/liblvvetx_3.21.15.so:system/vendor/lib/liblvvetx_3.21.15.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/hw/camera.universal3470.so:system/vendor/lib/hw/camera.universal3470.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/hw/hwcomposer.exynos3.so:system/vendor/lib/hw/hwcomposer.exynos3.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/hw/keystore.exynos3.so:system/vendor/lib/hw/keystore.exynos3.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/hw/lights.exynos3.so:system/vendor/lib/hw/lights.exynos3.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/hw/power.exynos3.so:system/vendor/lib/hw/power.exynos3.so \
    vendor/samsung/gardaltetmo/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/gardaltetmo/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/gardaltetmo/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/gardaltetmo/proprietary/bin/lpm:system/bin/lpm \
    vendor/samsung/gardaltetmo/proprietary/bin/sensorservice:system/bin/sensorservice \
    vendor/samsung/gardaltetmo/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/gardaltetmo/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/gardaltetmo/proprietary/media/Disconnected.qmg:system/media/Disconnected.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_batteryerror.qmg:system/media/battery_batteryerror.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/gardaltetmo/proprietary/media/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/02010000080300030000000000000000.tlbin:system/app/mcRegistry/02010000080300030000000000000000.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/03010000080300030000000000000000.tlbin:system/app/mcRegistry/03010000080300030000000000000000.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/ffffffff000000000000000000000009.tlbin:system/app/mcRegistry/ffffffff000000000000000000000009.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/ffffffff000000000000000000000018.tlbin:system/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/gardaltetmo/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/bcmdhd_apsta.bin_b2:system/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/bcmdhd_mfg.bin_b2:system/etc/wifi/bcmdhd_mfg.bin_b2 \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/bcmdhd_p2p.bin_b2:system/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/bcmdhd_sta.bin_b2:system/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/gardaltetmo/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/gardaltetmo/proprietary/etc/srm.bin:system/etc/srm.bin

